#!/usr/bin/env bash
if [ -f "/tmp/a_stream.pid" ]; then
   pid=`cat /tmp/a_stream.pid`
else
   pid=0
fi
if [ -e /proc/$pid -a /proc/$pid/exe ]; then
    if [[ $@ == **stop** ]]; then
        echo "Monitor stream stoped"
        kill $pid
    fi
else
	cvlc pulse://alsa_output.pci-0000_00_1b.0.analog-stereo.monitor --sout '#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100}: standard{access=http,dst=:8080/audio.mp3}' > /dev/null 2>&1 & 
	echo $! > /tmp/a_stream.pid
	echo Your monitor audio streams at: http://`hostname -I|cut -d' ' -f1`:8080/audio.mp3
fi